import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./global.css";
import DefaultLayout from "@/layouts/DefaultLayout";

const poppins = Poppins({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Nguyen Viet Manh | Front-end Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
